require('config.nvimtree').setup({
  log = {
    enable = true,
    types = {
      dev = true,
    },
  },
})

local log = require("nvim-tree.log")

pcall(vim.api.nvim_del_autocmd, vim.g.test_au1)

vim.g.test_au1 = vim.api.nvim_create_autocmd({
  "BufAdd",
  "BufDelete",
  "BufEnter",
  "BufFilePost",
  "BufFilePre",
  "BufHidden",
  "BufLeave",
  "BufModifiedSet",
  "BufNew",
  "BufNewFile",
  "BufRead",
  "BufReadPost",
  "BufReadCmd",
  "BufReadPre",
  "BufUnload",
  "BufWinEnter",
  "BufWinLeave",
  "BufWipeout",
  "BufWrite",
  "BufWritePre",
  "BufWriteCmd",
  "BufWritePost",
  "ChanInfo",
  "ChanOpen",
  "CmdUndefined",
  "CmdlineChanged",
  "CmdlineEnter",
  "CmdlineLeave",
  "CmdwinEnter",
  "CmdwinLeave",
  "ColorScheme",
  "ColorSchemePre",
  "CompleteChanged",
  "CompleteDonePre",
  "CompleteDone",
  "CursorHold",
  "CursorHoldI",
  "CursorMoved",
  "CursorMovedI",
  "DiffUpdated",
  "DirChanged",
  "DirChangedPre",
  "ExitPre",
  "FileAppendCmd",
  "FileAppendPost",
  "FileAppendPre",
  "FileChangedRO",
  "FileChangedShell",
  "FileChangedShellPost",
  "FileReadCmd",
  "FileReadPost",
  "FileReadPre",
  "FileType",
  "FileWriteCmd",
  "FileWritePost",
  "FileWritePre",
  "FilterReadPost",
  "FilterReadPre",
  "FilterWritePost",
  "FilterWritePre",
  "FocusGained",
  "FocusLost",
  "FuncUndefined",
  "UIEnter",
  "UILeave",
  "InsertChange",
  "InsertCharPre",
  "InsertEnter",
  "InsertLeavePre",
  "InsertLeave",
  "MenuPopup",
  "ModeChanged",
  "OptionSet",
  "QuickFixCmdPre",
  "QuickFixCmdPost",
  "QuitPre",
  "RemoteReply",
  "SearchWrapped",
  "RecordingEnter",
  "RecordingLeave",
  "SessionLoadPost",
  "ShellCmdPost",
  "Signal",
  "ShellFilterPost",
  "SourcePre",
  "SourcePost",
  "SourceCmd",
  "SpellFileMissing",
  "StdinReadPost",
  "StdinReadPre",
  "SwapExists",
  "Syntax",
  "TabEnter",
  "TabLeave",
  "TabNew",
  "TabNewEntered",
  "TabClosed",
  "TermOpen",
  "TermEnter",
  "TermLeave",
  "TermClose",
  "TermResponse",
  "TextChanged",
  "TextChangedI",
  "TextChangedP",
  "TextChangedT",
  "TextYankPost",
  "VimEnter",
  "VimLeave",
  "VimLeavePre",
  "VimResized",
  "VimResume",
  "VimSuspend",
  "WinClosed",
  "WinEnter",
  "WinLeave",
  "WinNew",
  "WinScrolled",
  "WinResized",
}, {
  callback = function(ev)
    log.line("dev", [[%-2d, %-3.3f [%41s] "%8s" (%8s) %18s: '%31s' -> '%31s']], os.clock(), ev.buf,
      string.sub(ev.file, #ev.file - 40, #ev.file), vim.v.option_type, vim.v.option_command, ev.match,
      string.sub(vim.v.option_old, #vim.v.option_old - 30, #vim.v.option_old),
      string.sub(vim.v.option_new, #vim.v.option_new - 30, #vim.v.option_new))
  end,
})
